CREATE TABLE IF NOT EXISTS DORM_LOOKUP_ITEM
(
    ID                   BIGINT       NOT NULL COMMENT '主键',
    CREATED_BY           VARCHAR(32)  NOT NULL COMMENT '创建人',
    CREATED_DATE         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    LAST_MODIFIED_BY     VARCHAR(32)  NOT NULL COMMENT '最后更新人',
    LAST_MODIFIED_DATE   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后更新时间',
    CLASSIFY_CODE        VARCHAR(255) NOT NULL COMMENT '快码分类CODE',
    CLASSIFY_PARENT_CODE VARCHAR(255) NULL COMMENT '父快码分类CODE',
    CLASSIFY_PARENT_NAME VARCHAR(255) NULL COMMENT '父快码分类名称',
    ITEM_ATTR1           VARCHAR(255) NULL COMMENT '扩展属性1',
    ITEM_ATTR2           VARCHAR(255) NULL COMMENT '扩展属性2',
    ITEM_ATTR3           VARCHAR(255) NULL COMMENT '扩展属性3',
    ITEM_ATTR4           VARCHAR(255) NULL COMMENT '扩展属性4',
    ITEM_ATTR5           VARCHAR(255) NULL COMMENT '扩展属性5',
    ITEM_ATTR6           VARCHAR(255) NULL COMMENT '扩展属性6',
    ITEM_CODE            VARCHAR(255) NOT NULL COMMENT '快码明细项CODE',
    ITEM_DESC            VARCHAR(255) NULL,
    ITEM_INDEX           INT          NULL,
    ITEM_NAME            VARCHAR(255) NOT NULL COMMENT '快码明细项名称',
    PARENT_CODE          VARCHAR(255) NULL COMMENT '父快码明细项CODE',
    STATUS               INT          NULL
) COMMENT ='快码明细项', ENGINE = INNODB;